# Generated by Django 2.2.24 on 2025-01-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20250109_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonsEntity',
            new_name='PokemonEntity',
        ),
    ]
