# Generated by Django 2.2.24 on 2025-01-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20250112_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_on_the_map', to='pokemon_entities.Pokemon', verbose_name='покемон'),
        ),
    ]
